<?php

namespace Database\Factories;

use App\Models\Plan;
use App\Models\Subscription;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Subscription>
 */
class SubscriptionFactory extends Factory
{
    protected $model = Subscription::class;

    public function definition(): array
    {
        // Start date for subscription
        $startAt = now();

        // Create user and get tenant_id
        $user = User::factory()->create();
        $tenantId = $user->tenant_id;

        // Create plan
        $plan = Plan::factory()->create();

        return [
            'tenant_id' => $tenantId,
            'user_id' => $user->id,
            'plan_id' => $plan->id,
            'status' => Subscription::STATUS_ACTIVE,
            'starts_at' => $startAt,
            'ends_at' => (clone $startAt)->addMonth(),
            'renewal_at' => (clone $startAt)->addMonth(),
            'canceled_at' => null,
            'metadata' => [
                'auto_renew' => true,
                'notes' => 'Generated by factory for testing',
            ],
        ];
    }
}
