@extends('layouts.customer.dashboard')
@section('title', __('poultry.titles.alerts'))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/pages/livestock.css') }}">@endpush
@section('content')
<div class="container py-4 livestock-page">
    <div class="page-head"><h2 class="page-title">{{ __('poultry.titles.alerts') }}</h2><a class="btn btn-outline-white" href="{{ route('customer.poultry.broiler-cycles.index', ['locale' => $currentLocale]) }}">{{ __('poultry.actions.back') }}</a></div>
    <div class="card-block mb-3"><h5 class="section-title">{{ __('poultry.alerts.high_mortality') }}</h5><div class="table-container"><table class="table registry-table mb-0"><thead><tr><th>{{ __('poultry.fields.cycle_number') }}</th><th>{{ __('poultry.fields.total_mortality') }}</th><th>{{ __('poultry.fields.mortality_rate') }}</th><th>{{ __('poultry.fields.actions') }}</th></tr></thead><tbody>@forelse($highMortalityCycles as $cycle)<tr><td>{{ $cycle->cycle_number }}</td><td>{{ $cycle->total_mortality }}</td><td>{{ $cycle->mortality_rate }}%</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('customer.poultry.broiler-cycles.show', ['locale' => $currentLocale, 'broiler_cycle' => $cycle->id]) }}">{{ __('poultry.actions.view') }}</a></td></tr>@empty<tr><td colspan="4">{{ __('poultry.empty.no_alerts') }}</td></tr>@endforelse</tbody></table></div></div>
    <div class="card-block"><h5 class="section-title">{{ __('poultry.alerts.near_slaughter') }}</h5><div class="table-container"><table class="table registry-table mb-0"><thead><tr><th>{{ __('poultry.fields.cycle_number') }}</th><th>{{ __('poultry.fields.started_at') }}</th><th>{{ __('poultry.fields.age_days') }}</th><th>{{ __('poultry.fields.actions') }}</th></tr></thead><tbody>@forelse($slaughterDueCycles as $cycle)<tr><td>{{ $cycle->cycle_number }}</td><td>{{ $cycle->started_at?->format('Y-m-d') }}</td><td>{{ $cycle->age_days }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('customer.poultry.broiler-cycles.show', ['locale' => $currentLocale, 'broiler_cycle' => $cycle->id]) }}">{{ __('poultry.actions.view') }}</a></td></tr>@empty<tr><td colspan="4">{{ __('poultry.empty.no_alerts') }}</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
