@extends('layouts.customer.dashboard')
@section('title', __('poultry.titles.layer_flock_details'))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/pages/livestock.css') }}">@endpush
@section('content')
<div class="container py-4 livestock-page">
    <div class="page-head"><h2 class="page-title">{{ __('poultry.titles.layer_flock_details') }}: {{ $flock->flock_number }}</h2><a class="btn btn-outline-white" href="{{ route('customer.poultry.layer-flocks.index', ['locale' => $currentLocale]) }}">{{ __('poultry.actions.back') }}</a></div>
    @include('dashboard.customer.poultry.partials.flash')
    <div class="card-block mb-3"><div class="row g-3"><div class="col-md-3"><strong>{{ __('poultry.fields.total_egg_revenue') }}:</strong> {{ $flock->total_egg_revenue }}</div><div class="col-md-3"><strong>{{ __('poultry.fields.total_feed_cost') }}:</strong> {{ $flock->total_feed_cost }}</div><div class="col-md-3"><strong>{{ __('poultry.fields.total_mortality') }}:</strong> {{ $flock->total_mortality }}</div><div class="col-md-3"><strong>{{ __('poultry.fields.net_profit') }}:</strong> {{ $flock->net_profit }}</div></div></div>
    <div class="card-block mb-3"><h5 class="section-title">{{ __('poultry.actions.record_egg_log') }}</h5><form method="POST" action="{{ route('customer.poultry.layer-flocks.egg-logs.store', ['locale' => $currentLocale, 'layer_flock' => $flock->id]) }}" class="row g-3">@csrf<div class="col-md-2"><input type="date" name="production_date" class="form-control" required></div><div class="col-md-2"><input type="number" min="0" name="eggs_count" class="form-control" placeholder="{{ __('poultry.fields.eggs_count') }}" required></div><div class="col-md-2"><input type="number" step="0.01" min="0" name="sale_price" class="form-control" placeholder="{{ __('poultry.fields.sale_price') }}" required></div><div class="col-md-2"><input type="number" step="0.01" min="0" name="daily_feed_cost" class="form-control" placeholder="{{ __('poultry.fields.daily_feed_cost') }}" required></div><div class="col-md-2"><input type="number" min="0" name="damaged_count" class="form-control" placeholder="{{ __('poultry.fields.damaged_count') }}"></div><div class="col-md-2"><button class="btn btn-primary-green w-100">{{ __('poultry.actions.save') }}</button></div></form></div>
    <div class="card-block"><h5 class="section-title">{{ __('poultry.actions.record_mortality') }}</h5><form method="POST" action="{{ route('customer.poultry.layer-flocks.mortalities.store', ['locale' => $currentLocale, 'layer_flock' => $flock->id]) }}" class="row g-3">@csrf<div class="col-md-3"><input type="date" name="mortality_date" class="form-control" required></div><div class="col-md-3"><input type="number" min="1" name="quantity" class="form-control" placeholder="{{ __('poultry.fields.quantity') }}" required></div><div class="col-md-4"><input type="text" name="notes" class="form-control" placeholder="{{ __('poultry.fields.notes') }}"></div><div class="col-md-2"><button class="btn btn-primary-green w-100">{{ __('poultry.actions.save') }}</button></div></form></div>
</div>
@endsection
