@extends('layouts.customer.dashboard')
@section('title', __('poultry.titles.chicken_breed_details'))
@push('styles')<link rel="stylesheet" href="{{ asset('assets/css/pages/livestock.css') }}">@endpush
@section('content')
<div class="container py-4 livestock-page">
    <div class="page-head"><h2 class="page-title">{{ __('poultry.titles.chicken_breed_details') }}: {{ $breed->code }}</h2><a class="btn btn-outline-white" href="{{ route('customer.poultry.chicken-breeds.index', ['locale' => $currentLocale]) }}">{{ __('poultry.actions.back') }}</a></div>
    @include('dashboard.customer.poultry.partials.flash')
    <div class="card-block mb-3"><div class="row g-3"><div class="col-md-3"><strong>{{ __('poultry.fields.breed_type') }}:</strong> {{ __('poultry.options.' . $breed->breed_type) }}</div><div class="col-md-3"><strong>{{ __('poultry.fields.purchase_amount') }}:</strong> {{ $breed->purchase_amount }}</div><div class="col-md-3"><strong>{{ __('poultry.fields.female_count') }}:</strong> {{ $breed->female_count }}</div><div class="col-md-3"><strong>{{ __('poultry.fields.male_count') }}:</strong> {{ $breed->male_count }}</div></div></div>
    <div class="card-block mb-3"><h5 class="section-title">{{ __('poultry.actions.record_breed_egg_log') }}</h5><form method="POST" action="{{ route('customer.poultry.chicken-breeds.egg-logs.store', ['locale' => $currentLocale, 'chicken_breed' => $breed->id]) }}" class="row g-3">@csrf<div class="col-md-2"><input type="date" name="production_date" class="form-control" required></div><div class="col-md-2"><input type="number" min="0" name="eggs_count" class="form-control" placeholder="{{ __('poultry.fields.eggs_count') }}" required></div><div class="col-md-2"><input type="number" min="0" name="fertilized_count" class="form-control" placeholder="{{ __('poultry.fields.fertilized_count') }}"></div><div class="col-md-2"><input type="number" min="0" name="unfertilized_count" class="form-control" placeholder="{{ __('poultry.fields.unfertilized_count') }}"></div><div class="col-md-3"><input type="text" name="notes" class="form-control" placeholder="{{ __('poultry.fields.notes') }}"></div><div class="col-md-1"><button class="btn btn-primary-green w-100">{{ __('poultry.actions.save') }}</button></div></form></div>
    <div class="table-container"><table class="table registry-table mb-0"><thead><tr><th>{{ __('poultry.fields.production_date') }}</th><th>{{ __('poultry.fields.eggs_count') }}</th><th>{{ __('poultry.fields.fertilized_count') }}</th><th>{{ __('poultry.fields.unfertilized_count') }}</th><th>{{ __('poultry.fields.notes') }}</th></tr></thead><tbody>@forelse($breed->eggLogs as $log)<tr><td>{{ $log->production_date?->format('Y-m-d') }}</td><td>{{ $log->eggs_count }}</td><td>{{ $log->fertilized_count }}</td><td>{{ $log->unfertilized_count }}</td><td>{{ $log->notes ?? '-' }}</td></tr>@empty<tr><td colspan="5">{{ __('poultry.empty.no_egg_logs') }}</td></tr>@endforelse</tbody></table></div>
</div>
@endsection
